[versions]
coil = "2.2.1"

[libraries]
coil = { module = "io.coil-kt:coil", version.ref = "coil" }
coil-compose = { module = "io.coil-kt:coil-compose", version.ref = "coil" }

[bundles]
coil = ["coil", "coil-compose"]

[plugins]